version: 2.1


jobs:
  build-and-deploy:
    machine:
      image: ubuntu-2204:2023.10.1
    environment:
      IMAGE_TAG: "1.4.<<pipeline.number>>"
      DOCKER_IMAGE: "darkeater/actividad4"
      HELM_VALUES_PATH: "charts/server/values.yaml"
    steps:
      - checkout

      - run:
          name: Install Python and dependencies
          command: |
            sudo apt update
            sudo apt install -y python3 python3-pip
            pip3 install flask

      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
            docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest
            docker push $DOCKER_IMAGE:$IMAGE_TAG
            docker push $DOCKER_IMAGE:latest

      - run:
          name: Update Helm values.yaml
          command: |
            sed -i "s/tag:.*/tag: $IMAGE_TAG/" $HELM_VALUES_PATH

      - run:
          name: Commit and Push Helm Update
          command: |
            git config --global user.email "zoe19902@gmail.com"
            git config --global user.name "Daniel19902"
            git remote set-url origin https://x-access-token:$GH_PAT@github.com/Daniel19902/servicio-microservice-demo.git
            git add $HELM_VALUES_PATH
            git commit -m "Update image tag to $IMAGE_TAG"
            git push origin HEAD:main

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/