version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout

      - run:
          name: Instalar dependencias
          working_directory: ./server
          command: npm install

      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Build y Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker build -t darkeater/actividad4:1.5.0 -t darkeater/actividad4:latest ./server
            docker push darkeater/actividad4:1.5.0
            docker push darkeater/actividad4:latest

      - run:
          name: Actualizar tag en Helm values.yaml
          command: sed -i "s/tag:.*/tag: 1.5.0/" charts/server/values.yaml

      - run:
          name: Commit and Push Helm Update
          command: |
            git config --global user.email "zoe19902@gmail.com"
            git config --global user.name "Daniel19902"
            git remote set-url origin https://x-access-token:$GH_PAT@github.com/Daniel19902/servicio-microservice-demo.git
            git add $HELM_VALUES_PATH
            git commit -m "Update image tag to $IMAGE_TAG"
            git push origin HEAD:main


workflows:
  version: 2
  ci_cd:
    jobs:
      - build:
          filters:
            branches:
              only: main
