apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: servicio-microservice-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /testPath
          pathType: ImplementationSpecific
          backend:
            service:
              name: servicio-microservice-demo
              port:
                number: 4530
