apiVersion: v1
kind: Service
metadata:
  name: servicio-microservice-demo
spec:
  type: LoadBalancer
  ports:
    - port: 4530
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: servicio-microservice-demo
