name: CI/CD

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./server
        run: npm install
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push Docker Image
        id: docker_build
        with:
          image: darkeater/actividad4
          tags: 1.4.0,latest
          dockerfile: Dockerfile
          registry: docker.io
          username: darkeater
          password: daniel1234
          context: ./server
          pushImage: true
      - name: Set image tag variable
        run: echo "IMAGE_TAG=1.4.0" >> $GITHUB_ENV

      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" charts/server/values.yaml

      - name: Commit and Push Helm update
        run: |
          git config --global user.email "zoe19902@gmail.com"
          git config --global user.name "Daniel19902"
          git add charts/server/values.yaml
          git commit -m "Update image tag to ${IMAGE_TAG}"
          git push


