name: CI/CD

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./server
        run: npm install
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push Docker Image
        with:
          image: darkeater/actividad4
          tags: 1.3.0,latest
          dockerfile: Dockerfile
          registry: docker.io
          username: darkeater
          password: daniel1234
          pushImage: true
